name = "ArsMateria Theme"
description = "A theme using the arsmateria styling"
license = "MIT"
homepage = "https://github.com/getzola/hyde"
# The minimum version of Zola required
# min_version = "0.4.0"
# An optional live demo URL
demo = ""

# Any variable there can be overridden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
subtitle = "Subtitle"
author = "Author Name"
copyright_year = "20XX"
default_description = "Default Description"

# The theme author info: you!
[author]
name = "Brady O'Leary"
homepage = "https://deadcomputersociety.com"
repo = "https://github.com/mboleary/arsmateria-zola-theme"